# Generated by Django 5.0.6 on 2024-07-02 04:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsheet',
            name='file',
            field=models.FileField(upload_to=dashboard.models.uploaded_sheet_path),
        ),
    ]
