# Generated by Django 5.0.6 on 2024-07-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_missingdatafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missingdatafile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='missingdatafile',
            name='no_of_rows',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_row_index', models.BigIntegerField()),
                ('end_row_index', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('missing_data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='dashboard.missingdatafile')),
            ],
        ),
        migrations.RemoveField(
            model_name='missingdatafile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='missingdatafile',
            name='assigned_user',
        ),
    ]
