# Generated by Django 5.0.6 on 2024-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_missingdatafile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdatafile',
            name='no_of_rows',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
