# Generated by Django 5.0.6 on 2024-07-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_missingdatafile_no_of_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workassignment',
            old_name='end_row_index',
            new_name='end_row',
        ),
        migrations.RenameField(
            model_name='workassignment',
            old_name='start_row_index',
            new_name='start_row',
        ),
    ]
