# Generated by Django 5.0.6 on 2024-07-10 12:40

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_end_row_index_workassignment_end_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='assigned_file',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.assigned_missing_data_file_path),
        ),
    ]
