# Generated by Django 5.0.6 on 2024-08-08 11:23

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_workassignment_assigned_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='skipped_rows_file',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.skipped_rows_file_path),
        ),
    ]
